# Generated by Django 2.0 on 2017-12-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20171206_2328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskList',
            new_name='DoTaskList',
        ),
    ]
