# Generated by Django 2.0 on 2017-12-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20171206_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotasklist',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
